services:
  app:
    image: phonebook-front
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - API_URL=http://localhost:4000
        - WS_URL=ws://localhost:4000
    container_name: phonebook-front
 
  server:
    image: phonebook-backend
    ports:
      - 4000:4000
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

  debug-helper:
    image: busybox
    container_name: debug-helper